name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-all-ubuntu-bash:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run setup scripts with Bash
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "nobody@localhost"
        chmod +x ./test-all.sh
        ./test-all.sh

  test-all-macos-bash:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run setup scripts with Bash
      shell: bash
      run: |
        chmod +x ./test-all.sh
        echo "Test using bash"
        ./test-all.sh -s bash

  test-all-macos-zsh:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run setup scripts with Zsh
      shell: bash
      run: |
        chmod +x ./test-all.sh
        echo "Test using zsh"
        ./test-all.sh -s zsh

  test-basic-ubuntu-pwsh:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run PowerShell Core test scripts
      run: ./test.ps1
      shell: pwsh
